version = 0.1
[default.deploy.parameters]
stack_name = "godemo"
resolve_s3 = true
s3_prefix = "godemo"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
