AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda-go-proxy-api-demo-app

  SAM Template for lambda-go-proxy-api-demo-app

Globals:
  Function:
    Timeout: 5

Resources:
  DemoFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/query
      Architectures:
        - arm64
      Handler: bootstrap
      Runtime: provided.al2
      MemorySize: 1024
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
          - Sid: BedrockRuntime
            Effect: Allow
            Action:
            - bedrockruntime:InvokeModel
            - bedrock:InvokeModel
            Resource: '*'

      Events:
        ApiEvents:
          Type: Api
          Properties:
            Path: /query
            Method: POST
            RestApiId: !Ref DemoAPIGateway
            # Auth:
            #   ApiKeyRequired: true
      Environment:
        Variables:
          PARAM1: VALUE
    Metadata:
      BuildMethod: makefile
  DemoAPIGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
    Auth:
      ApiKeyRequired: true  # for all methods
      UsagePlan:
        CreateUsagePlan: PER_API
        Description: Usage plan for this API
        Quota:
          Limit: 500
          Period: DAY
        Throttle:
          BurstLimit: 100
          RateLimit: 50
        Tags:
          - Key: TagName
            Value: TagValue        

Outputs:
  APIGWEndpoint:
    Description: API Gateway Endpoint
    Value:
      Fn::Sub: https://${DemoAPIGateway}.execute-api.${AWS::Region}.amazonaws.com/dev/query
